### PR TITLE
Add tab and tasks table

### PR DESCRIPTION
**Pull request by Lumi3011**
Added tab for tasks table and also an empty table #416

### CODE REVIEW

**Comment by zoeself** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``REV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by amihaiemil** [comment]
@Lumi3011 arata ok. Poti oare schimba target-ul PR-ului? Sa nu ii facem merge in ``master`` ci in ``projectTasks``. 

Va mai dura putin pana terminam cu asta si va mai trebui intre timp sa facem un release din master, cel mai probabil :D

**Comment by Lumi3011** [comment]
@amihaiemil Done :D

**Comment by amihaiemil** [comment]
@Lumi3011 mersi :D

**Comment by Lumi3011** [comment]
Merci si eu :)

**Pull request merged**
