### PR TITLE
#160 Confirm on removing a contract from contributor dashboard.

### LINKED ISSUE #160: Add "Are You Sure?" Modal On Contributor Contract Remove
When the contributor marks one of their contracts for removal, we should have this popup, similarly to how it's done on project contracts tab.

### PR DESCRIPTION
**Pull request by criske**
Closes #160 

- also fixed bug where confirm dialog button click listener was leaking.

### CODE REVIEW

**Comment by criske** [comment]
@amihaiemil no bounty needed :D

**Comment by amihaiemil** [comment]
@charlesmike status

**Comment by charlesmike** [comment]
> @charlesmike status

@amihaiemil this ticket is not registered as a task, therefore I'm not working on it at the moment.

If you want me to take care of it, assign it to me or say "register".

**Comment by amihaiemil** [comment]
@charlesmike register

**Comment by charlesmike** [comment]
> @charlesmike register

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-11-07T16:18:59.137116``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@charlesmike status

**Comment by charlesmike** [comment]
> @charlesmike status

@amihaiemil this ticket is assigned to @amihaiemil since ``2020-11-04T16:18:59`` and it should be closed until ``2020-11-07T16:18:59``. Estimation is ``30`` minutes.

**Comment by amihaiemil** [comment]
@criske thank you!

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
