### PR TITLE
#223 Better Wallet Info

### LINKED ISSUE #223: Display Wallet Type for Contract
On the Contributor Dashboard page, for every Contract of the Contributor, we should display an icon letting the contributor know whether the Project uses a real wallet or a fake wallet.

EDIT: let's also display it on the Projects page (Contracts tab).

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #223 

* On the Contributor Dashboard page we display the wallet type for each Contract
* Fixed bug regarding the wallet pie chart + cleaned JS code.
* Fixed other small display bugs. 
* Added "Are you sure..." question modal for the Pay Invoice icon.

### CODE REVIEW

**Comment by charlesmike** [comment]
@amihaiemil thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-12-12T16:45:49.960091``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
