### PR TITLE
Adds footer

### LINKED ISSUE #20: Design the footer
Design the footer. It should contain things such as company address, terms and cod, privacy policy etc.

### PR DESCRIPTION
**Pull request by ANadrowski**
fixes #20. Adds footer and command to work in the responsive way.
As always, feel free to refuse it.
Thanks.

### CODE REVIEW

**Comment by amihaiemil** [comment]
@ANadrowski Well, the HTML looks ok and everything, but could you paste an image here, how does the footer actually look? :D

**Comment by ANadrowski** [comment]
@amihaiemil sure, take a look:

Screenshot from 2020-06-06 08-08-39

**Comment by amihaiemil** [comment]
@ANadrowski looks great, thanks!

**Comment by amihaiemil** [comment]
@rultor merge it

**Pull request merged**
