### PR TITLE
#327 Fixed Contributor Dashboard Tasks table issue links.

### LINKED ISSUE #327: Links to issues in the Tasks card on the Dashboard are broken
All issues links point to _http://self-xdsd.go.ro/contributor#_
issue-links-brocken

- Actual behaviour:
Links point to _http://self-xdsd.go.ro/contributor#_
- Expected behaviour:
Eash link should open the corresponding issue on Github.

### PR DESCRIPTION
**Pull request by criske**
Fixes #327 

Contract object passed to task table row wasn't have the `id.provider` property set.

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
no bounty needed, was a quick fix.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2021-01-14T10:26:12.492736``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@criske thanks!

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
