### PR TITLE
#244 After paying Invoice, new active Invoice is shown.

### LINKED ISSUE #244: Newly created invoices are not displayed when pressing the “See Tasks” button
1. GO to a contract
2. Pay an invoice -> Invoice is "Paid"
3. Press on the reload button for the paid invoice at step 2
**Expected result**: The new invoice should be displayed
**Actual result**:  The new invoice is not displayed until the contract list is refreshed
image

### PR DESCRIPTION
**Pull request by criske**
Fixes #244

- also empty Invoices can't be paid or downloaded as pdf anymore.

Self XDSD

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-12-20T14:22:05.315392``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
