### PR TITLE
Stripe country actualization

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by zoeself** [comment]
@valery1707 thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``REV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by valery1707** [comment]
Build failed to the authentication problem while transfering artifacts from https://maven.pkg.github.com/self-xdsd/self-core:

> [ERROR] Failed to execute goal on project self-web: Could not resolve dependencies for project com.selfxdsd:self-web:jar:0.0.15-SNAPSHOT: Failed to collect dependencies at com.selfxdsd:self-api:jar:0.0.98: Failed to read artifact descriptor for com.selfxdsd:self-api:jar:0.0.98: Could not transfer artifact com.selfxdsd:self-api:pom:0.0.98 from/to github (https://maven.pkg.github.com/self-xdsd/self-core): authentication failed for https://maven.pkg.github.com/self-xdsd/self-core/com/selfxdsd/self-api/0.0.98/self-api-0.0.98.pom, status: 401 Unauthorized

**Comment by amihaiemil** [comment]
@valery1707 to build the project locally you need to do this: https://github.com/self-xdsd/self-web#maven-settings

**Comment by valery1707** [comment]
Any updates?

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by amihaiemil** [comment]
@valery1707 are you working in Self, do you need these countries released soon?

**Pull request merged**
