### PR TITLE
Added error pages

### PR DESCRIPTION
**Pull request by Lumi3011**
Added pages 404 and 500 
Added image for every page #399

### CODE REVIEW

**Comment by zoeself** [comment]
@Lumi3011 thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by Lumi3011** [comment]
@amihaiemil I have added the pages and the images as you said and I tried to make them responsive. If you want, we can make the pages to look better on multiple devices, by not adding one image, but instead to make for eg on 404 page the robot one image and the logo another image and to align them with css along with the text. Let me know if you want to change it like that :D

**Comment by zoeself** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``REV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by amihaiemil** [comment]
@Lumi3011 arata ok, doar ca in imaginea de 404 e acel text cu "go to hompage" -- ala nu e ok acolo, user-ul va avea impresia ca e un link, cand defapt e doar parte din imagine

Screenshot 2021-03-26 at 14 39 44

Propozitia aceea ar trebui sa fie sub imagine cumva, sau mai bine scoate-o din imagine si vedem mai incolo daca o adaugam :D

**Comment by Lumi3011** [comment]
Ok, si de-asta de intrebasem daca sa nu folosim toata imaginea, dar ok, o modific pe asta sa nu mai fie ca un link. :D

**Comment by amihaiemil** [comment]
@Lumi3011 mersi! : D

**Pull request merged**
