### PR TITLE
#350 Fixed pm link on "managed by" project section.

### LINKED ISSUE #350: getProject.js: Wrong pm link for when project is on Gitlab.
Link for pm profile is hardcoded for Github. It should be created based on project provider base url (ex: "gitlab.com").
https://github.com/self-xdsd/self-web/blob/47a240122b2e97c4bf8204383068192e19440282/src/main/resources/public/js/getProject.js#L46-L51

### PR DESCRIPTION
**Pull request by criske**
Fixes #350

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
no bounty

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2021-01-28T16:26:39.061795``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2021-01-28T16:26:39). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
@criske thanks!

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
