### PR TITLE
#248 wallet pie chart is now updating when new limit is set

### PR DESCRIPTION
**Pull request by fellahi-ali**
Fix for #248 
I'm not sure this is best way to fix that issue; 
WDYT @criske?

### CODE REVIEW

**Comment by charlesmike** [comment]
@fellahi-ali thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2021-01-15T23:06:12.747134``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by criske** [comment]
@fellahi-ali for separation of concerns, I think that call would be better to be moved to `wallet.js` in `installUpdateCashLimitPopover` callback function (where `cashLimitColor` is updated too):
https://github.com/self-xdsd/self-web/blob/f601e082c374e20564696da79b56b11804593b7b/src/main/resources/public/js/wallets.js#L111-L121

**Comment by fellahi-ali** [comment]
@amihaiemil no payment for this one :)

**Comment by amihaiemil** [comment]
@fellahi-ali @criske thanks!

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
