### PR TITLE
#359 Allow usernames with dot in contract 

### LINKED ISSUE #359: Allow Dot Add Contract UserName Validation
On the Project Contracts Tab, in the Add Contract formular, let's change the validation to also allow dots in the username. At the moment they are forbidden:

This change has to be done in the backend validator and probably also somewhere in the front-end, if it's present.

Screenshot 2021-02-07 at 10 06 07

### PR DESCRIPTION
**Pull request by fellahi-ali**
Fixes #359

### CODE REVIEW

**Comment by charlesmike** [comment]
@fellahi-ali thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2021-02-15T19:30:24.483428``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2021-02-15T19:30:24). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
@fellahi-ali looks good. I just escaped the dot in the regex ``\\.`` because the dot in RegEx means "any character". If you want it to mean actual dot, it has to be escaped :D

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by fellahi-ali** [comment]
> @fellahi-ali looks good. I just escaped the dot in the regex `\\.` because the dot in RegEx means "any character". If you want it to mean actual dot, it has to be escaped :D

@amihaiemil many thanks :)
Actually I was curious about that escape char `\\` because I found you using it in `RepoInput.name` validation, but what confused me is the _Check Regex_ feature in IDEA and also the unit test, because even without using the escaping the regex will not accept other chars (or do I miss something?):
regex-valid
regex-invalid

**Comment by amihaiemil** [comment]
@fellahi-ali I'm not sure how that intellij plugin works :D 

But in general, the . in regex means "any character" so I always escape it, just to be sure.

**Pull request merged**
