### PR TITLE
Resolved tooltip flickering

### LINKED ISSUE #158: Tooltip flickers when hover the "mark for removal" icon.
On my end, tooltip flickers when hover the "mark for removal" icon in Project - Contracts table.
Also the tooltip is displaced.
mark_for_delete_tooltip_flicker

### PR DESCRIPTION
**Pull request by Lumi3011**
Fixes #158. Tooltip is not flickering now. I also move it on the left of the icon so the user can see better which icon the tooltip is assigned to.

### CODE REVIEW

**Comment by charlesmike** [comment]
@Lumi3011 thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-11-07T16:28:59.024597``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@Lumi3011 thanks!

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
