### PR TITLE
#290 Settings Tab, Delete Project Implemented

### LINKED ISSUE #290: Implement Settings Tab
Let's implement the Project Settings tab and then the Remove Project button.

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #290 

Implemented Settings tab and the Delete Project button.
Delete Project button is active only if the Project has 0 Contracts (all contracts have been removed).
Backend endpoints for contractCound and deleteProject implemented.
Logging for ProjectsApi class.
Other small improvements.

### CODE REVIEW

**Comment by charlesmike** [comment]
@amihaiemil thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-12-30T13:45:05.708093``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
