### PR TITLE
#215 Show "Loading" Circle When Loading Contracts.

### LINKED ISSUE #215: Show "Loading" Circle When Loading Contracts
On the project page, Contracts tab, we should show the Loading circle. At the moment, it's not used there and the page looks like this (until the projects are displayed):

Screenshot 2020-12-02 at 11 19 56

### PR DESCRIPTION
**Pull request by criske**
- added a helper function to show loading animation to any data table.
(this should be called before ajax call)
- removed dead code of loading logic.

Self XDSD

closes #215

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-12-06T12:10:51.015577``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@criske thanks!

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
