### PR TITLE
#249 "Update cash limit" pop-up closes when clicking outside of it.

### LINKED ISSUE #249: When clicking outside of the "Update cash limit" pop-up this should be closed
1. Go to the **Wallets** tab of a certain repository
2. Open the "Update cash limit" pop-up
3. Click outside the pop-up 
Expected result: Pop-up should be closed
Actual result: Pop-up remain opened and when you navigate to a different tab, this will still be displayed
image

### PR DESCRIPTION
**Pull request by criske**
Fixes #249 

Self XDSD

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
no bounty

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-12-21T11:43:05.354282``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
