### PR TITLE
#347 Global profile variable.

### LINKED ISSUE #347: head.html:  Global profile variable.
Same as global provider, we should have a global js variable `profile` that will be initialized when   `/api/users/self` call in `head.html` is successful. (`globalProfile.change(data)`)
https://github.com/self-xdsd/self-web/blob/a2d3bd04d47c816729140d11776dfad89792360b/src/main/resources/templates/head.html#L50-L55
After that:
- in getProject.js replace  `/api/users/self` call with `globalProfile.onChange(...)`
 https://github.com/self-xdsd/self-web/blob/a2d3bd04d47c816729140d11776dfad89792360b/src/main/resources/public/js/getProject.js#L11-L13 
- in "user.html", remove  thymeleaf directives (`th`) and create a script where, when globalProfile changes, updates "username", "provider", "email" and "providerLink" elements. (also `Model` from `UserController#index` is not needed anymore).

### PR DESCRIPTION
**Pull request by criske**
closes #347

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
no bounty pls :D

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2021-01-28T12:06:11.419174``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@criske thank you, looks good!

**Comment by amihaiemil** [comment]
@criske I deployed the latest self-web in Test, we can now use GitLab there :)

**Comment by criske** [comment]
@amihaiemil thanks for notice, btw there is a small bug with this PR.. `capitalize()` extension is not recognized in getAndAddContracts.js. I'll fix asap

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
