### PR TITLE
#182 WalletsApi is now using user projects to find a project.

### LINKED ISSUE #182: WalletsApi.java: Update WalletsApi endpoints t...
The puzzle ``179-5898565e`` originating from #179 has to be resolved:

https://github.com/self-xdsd/self-web/blob/d04274791aa658a4bbfc29711bab1dce04c44aa5/src/main/java/com/selfxdsd/selfweb/api/WalletsApi.java#L58-L61

"Update WalletsApi endpoints to use `this.user.projects` when searching for a project (where is the case). Right now most of them are using `this.self.projects` meaning that any user can have access to other users wallets.".

It was created by cristianpela on 2020-11-15T12:13:13Z. Estimation is ``15 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

### PR DESCRIPTION
**Pull request by criske**
Fixes #182

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
no bounty needed.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-11-20T12:10:30.938449``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@criske thanks!

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
