### PR TITLE
#347 Global profile variable.

### PR DESCRIPTION
**Pull request by criske**
- js shenanigans wrong name for capitalize string extension.

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2021-01-28T16:06:37.735648``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@criske I noticed there is another bug: the Contracts tab button on the Project page is not working. Can you have a look please? :D

**Comment by criske** [comment]
@amihaiemil that was the problem, typed the name wrong.. this fixes it :D

**Comment by amihaiemil** [comment]
@criske great, thanks :D

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
