### PR TITLE
#241. Fixed typo in "Update contract" card.

### LINKED ISSUE #241: Typo in "Update contract" card
image

### PR DESCRIPTION
**Pull request by criske**
Fixes #241

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
no bounty for this one :D

--
@amihaiemil Btw my mockup about updating contracts by editing the `Hourly Rate` cell is done. If you ever want to integrate this aproach into `self-web` just let me know :D

Tables

https://github.com/criske/editable-datatable

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2021-01-10T12:59:11.056284``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@criske 

> Btw my mockup about updating contracts by editing the Hourly Rate cell is done

That's a good idea, but let's do it later, after Prod release. Thanks!

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
