### PR TITLE
#306 Fixed Options Buttons Don't Work On 2+ Pages Of Table.

### LINKED ISSUE #306: Options Buttons Don't Work On 2nd Page Of Table
On the Contributor Dashboard page, the Options buttons (Contract Agenda, Mark For Removal) are not working on the second and later pages. This might also be a problem in other tables. As far as I can tell, it's related to the new table loading approach. 

Screenshot 2021-01-02 at 11 09 24

The problem is most likely that the event listeners are only appended to the elements visible on the first page of the table.

### PR DESCRIPTION
**Pull request by criske**
Fixes #306

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
@amihaiemil There is a visual bug still: when mark a contract for removal in Projects' contract tab and we're on another page, the whole table is reloaded from page 1 and losing the current page. `markContractForRemoval` in Contributor dashboard is doing this correctly though.
This bug should be covered by #285

--
btw no bounty needed for this pr.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2021-01-05T14:38:48.784120``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@criske thanks, looks good!

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
