### PR TITLE
Tests for JsonContract output class

### PR DESCRIPTION
**Pull request by Lumi3011**
Wrote the UnitTests for JsonContract #162

### CODE REVIEW

**Comment by charlesmike** [comment]
@Lumi3011 thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-11-08T14:28:58.898243``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@Lumi3011 looks nice. Can you also remove the ``todo`` from [here](https://github.com/self-xdsd/self-web/blob/b8fdb009c4a09feaf37f2a735199f05aaa845627/src/test/java/com/selfxdsd/selfweb/api/output/JsonProjectTestCase.java#L44-L45) and add another todo to continue work on another output class? (choose one you like). 

A ``todo`` looks like this:

```
@todo #162:30min Continue writing unit tests for the JSON output classes.
 We can continue with class XYZ.
```

``#162`` is the ticket where the todo was created and ``30min`` is the estination. Also pay attention at lines ``2..n``, they have to start with a space (they should be alligned with the ``t``, not the ``@``).

These todos are converted into actual Github Issues and then the issues are closed when the todos are removed.

**Comment by Lumi3011** [comment]
@amihaiemil So what ticket number should I assign?

**Comment by amihaiemil** [comment]
@Lumi3011 ``#162``, that's the ticket you've solved now and where you're adding the todo

**Comment by Lumi3011** [comment]
@amihaiemil Ok then. I taught that I should add a new ticket number. Thanks!

**Comment by Lumi3011** [comment]
@amihaiemil  Done :D

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by amihaiemil** [comment]
@rultor merge

**Comment by amihaiemil** [comment]
@rultor try to merge again

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by amihaiemil** [comment]
@Lumi3011 Last failure is not because of you. I'll fix it in a ticket soon.

**Comment by Lumi3011** [comment]
@amihaiemil Ok :D

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
