### PR TITLE
Authenticated-357

### PR DESCRIPTION
**Pull request by Lumi3011**
Modified the authenticated avatar so it's displayed in row now. #357

### CODE REVIEW

**Comment by charlesmike** [comment]
@Lumi3011 thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2021-02-18T18:56:54.670178``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@Lumi3011 Deci, din cate vad, aplici acel CSS din JavaScript, doar pentru acele doua media width-uri. 

Practic, e acelasi CSS, insa aplicat elementelor doar in cazul ``default`` (deci daca autentificarea nu a mers) si in functie de acelasi mobile width. 

Looks good to me. Probabil ca nu e cea mai optima solutie, dar nici eu nu pot veni cu ceva mai bun si oricum, locuri de improvement sunt destule in tot front-endu.

Probabil anul asta il vom rescrie cu React sau Angular, sa fie mai la zi. Dar initial l-am scris babeste cu JQuery pentru ca nici macar nu stiam cum vreau sa arate (si daca nici aia nu stii, nu poti scrie React ca lumea). Acuma ca avem design-u, vom putea incerca.. . :D

**Comment by Lumi3011** [comment]
@amihaiemil Exact, asta am facut, solutia e destul de optima, mai putin acel listener care nu e pus. Si ar fi super sa rescriem in React, sa il optimizam, si daca vrei, ne uitam si pe design in viitor sa facem site-ul mai modern.

**Comment by amihaiemil** [comment]
@Lumi3011 da da, asta am in plan. Dar sa il vad lansat odata. Astept inca dupa niste hartii si pe final de Februarie cred ca suntem in Prod :)

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
