### PR TITLE
#411 Remove fake when real wallet is detected on listing.

### LINKED ISSUE #411: Empty Fake Wallet Div
I deployed the new self-web in Test Environment and I removed the Fake Wallets from the DB manually, for projects which already had a Real Wallet. 

Then, when I reload the page: 

Screenshot 2021-03-27 at 09 26 24

This bug did not occur when I tested the activation of the real wallet (where the fake wallet is deleted automatically). It seems to occur at the initial GET /wallets.

### PR DESCRIPTION
**Pull request by criske**
closes #411

### CODE REVIEW

**Comment by zoeself** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
@amihaiemil  problem was that fake wallet was static (in `project.html`) and not dynamically generated.

**Comment by zoeself** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``REV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by amihaiemil** [comment]
@criske thanks!

**Pull request merged**
