### PR TITLE
Wrote Unit Tests for JsonWallet

### PR DESCRIPTION
**Pull request by Lumi3011**
Finished UnitTest for JsonWallet output class #166

### CODE REVIEW

**Comment by charlesmike** [comment]
@Lumi3011 thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-11-13T18:27:21.572424``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@Lumi3011 Can you also remove the todo from JsonContractTestCase.java and add a new one in JsonWalletTestCase, to continue with the tests? Pick another class which you would like to continue with :D

**Comment by Lumi3011** [comment]
@amihaiemil Done :D

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
