### PR TITLE
#265 "Update cash limit" closes itself when limit updated.

### LINKED ISSUE #265: "Update cash limit" pop-up improvements
**Improvement 1:**
When updating the limit update, confirmation button should be a **check sign** not reload
image

**Improvement 2:**
After accepting the new limit, pop-up should close
image

### PR DESCRIPTION
**Pull request by criske**
Fixes #265

Self XDSD

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
no bounty

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-12-21T12:01:05.776876``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
