### PR TITLE
#203 Load Contracts Only on Tab Click.

### LINKED ISSUE #203: Load Contracts Only on Tab Click
On the Project page, we should load the Contracts only when the user clicks on the 'Contracts' tab.

At the moment, contracts area loaded together with the Project Overview tab and this is not always correct.

For example, the authenticated user may be an admin in the Organization which owns the repo, but we allow them to see only the Project Overview (they will not be able to load the contracts).

### PR DESCRIPTION
**Pull request by criske**
closes #203

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
@amihaiemil I think that's all, no bounty needed.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-12-04T11:00:56.103705``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@criske thank you!

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
