### PR TITLE
#198 Display all Invoices in Project Contracts Tab

### LINKED ISSUE #198: Project Page: Display Invoices of Contract
Analogous to how we display invoices of a Contract on the Contributor Dashboard page, we should also display a Contract's Invoices on the Project Page (Contracts Tab). At the moment, only the Tasks are displayed and the PO can only download the active Invoice.

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #198 

We now display all Invoices of a Contract in a table side-by-side with the Tasks (analogue to Contributor Dashboard page);
Adapted ContractsApi endpoints (GET invoices, GET invoice, PUT payInvoice);
Changes in the front-end;
Pulled out invoiceToPdf JS function in its own file and reused it (it was duplicated before);
Other minor changes in text and styling of Project Overview tab;

Screenshot:

Screenshot_2020-11-28 Self XDSD

### CODE REVIEW

**Comment by charlesmike** [comment]
@amihaiemil thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-12-01T09:41:51.794222``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
