### PR TITLE
#245 "Github Username" field err is not displayed when search anymore.

### LINKED ISSUE #245: Validation for "Github Username" field is still displayed after selecting a user for a new contract
1. Try to add a new contract
2. Search for a non-existing user -> Validation is displayed
3. Select a valid user
Expected result: Validation is not displayed anymore
Actual result: Validation is still displayed
image

### PR DESCRIPTION
**Pull request by criske**
Fixes #245

Self XDSD

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
no bounty

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-12-20T14:49:04.982738``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
@criske thank you!

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
