### PR TITLE
#161 Added update cash limit form for real wallet.

### LINKED ISSUE #161: Add "Update Cash Limit" Form
On the Project page, Wallets tab, "Real Wallet" card there should be a form with one numeric field, that will allow the PO to update the cash limit that we're allowed to use.

### PR DESCRIPTION
**Pull request by criske**
closes #161 

update_cash_limit

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-11-10T14:23:06.080999``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-11-10T14:23:06). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
@criske looks elegant, thanks!

Is the backend implemented too already? If not, can you leave a puzzle for it?

**Comment by criske** [comment]
@amihaiemil I've left a puzzle above the timeout call that simulates the network call.

**Comment by amihaiemil** [comment]
@criske great, thanks!

**Comment by amihaiemil** [comment]
@rultor merge it please

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
